# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-04-11 22:49
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('original_amount', models.DecimalField(decimal_places=2, max_digits=6)),
                ('discounted_amount', models.DecimalField(decimal_places=2, max_digits=6)),
                ('billing_method', models.CharField(max_length=200)),
            ],
        ),
    ]
