# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-04-28 11:14
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_auto_20170410_2251'),
    ]

    operations = [
        migrations.AddField(
            model_name='member',
            name='avatar',
            field=models.FileField(blank=True, upload_to=''),
        ),
    ]
