# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-04-08 02:56
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('games', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Purchase',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('datetime', models.DateTimeField(default=datetime.datetime(2017, 4, 8, 2, 56, 37, 191963))),
                ('original_amount', models.DecimalField(decimal_places=2, max_digits=6)),
                ('discounted_amount', models.DecimalField(decimal_places=2, max_digits=6)),
                ('billing_method', models.CharField(max_length=200)),
                ('game', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='games.Game')),
            ],
        ),
    ]
