# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-04-08 03:00
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('purchases', '0002_purchase_member'),
    ]

    operations = [
        migrations.AlterField(
            model_name='purchase',
            name='datetime',
            field=models.DateTimeField(default=datetime.datetime(2017, 4, 8, 3, 0, 6, 26509)),
        ),
    ]
