# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-04-10 14:51
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('purchases', '0006_auto_20170409_1912'),
    ]

    operations = [
        migrations.AlterField(
            model_name='purchase',
            name='datetime',
            field=models.DateTimeField(default=datetime.datetime(2017, 4, 10, 22, 51, 48, 253703)),
        ),
    ]
