# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-04-11 20:31
from __future__ import unicode_literals

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('purchases', '0013_auto_20170411_1112'),
    ]

    operations = [
        migrations.AlterField(
            model_name='purchase',
            name='datetime',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
