# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-04-11 22:49
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('purchases', '0014_auto_20170412_0431'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='purchase',
            name='billing_method',
        ),
        migrations.RemoveField(
            model_name='purchase',
            name='discounted_amount',
        ),
        migrations.RemoveField(
            model_name='purchase',
            name='original_amount',
        ),
    ]
