# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-04-08 03:00
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('users', '0001_initial'),
        ('purchases', '0003_auto_20170408_0300'),
    ]

    operations = [
        migrations.CreateModel(
            name='Reward',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('award_datetime', models.DateTimeField(default=datetime.datetime(2017, 4, 8, 3, 0, 6, 17304))),
                ('expiry_datetime', models.DateTimeField(default=datetime.datetime(2017, 8, 6, 3, 0, 6, 17391))),
                ('member', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.Member')),
                ('purchase', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='purchases.Purchase')),
            ],
        ),
    ]
