# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-04-08 08:14
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rewards', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reward',
            name='award_datetime',
            field=models.DateTimeField(default=datetime.datetime(2017, 4, 8, 16, 14, 7, 410184)),
        ),
        migrations.AlterField(
            model_name='reward',
            name='expiry_datetime',
            field=models.DateTimeField(default=datetime.datetime(2017, 8, 6, 16, 14, 7, 410221)),
        ),
    ]
