# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-04-09 11:12
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rewards', '0003_auto_20170409_1643'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reward',
            name='award_datetime',
            field=models.DateTimeField(blank=True, default=datetime.datetime.now),
        ),
        migrations.AlterField(
            model_name='reward',
            name='expiry_datetime',
            field=models.DateTimeField(blank=True, default=datetime.datetime.now),
        ),
    ]
