# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-04-11 20:31
from __future__ import unicode_literals

from django.db import migrations, models
import django.utils.timezone
import rewards.helpers


class Migration(migrations.Migration):

    dependencies = [
        ('rewards', '0004_auto_20170409_1912'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reward',
            name='award_datetime',
            field=models.DateTimeField(blank=True, default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='reward',
            name='expiry_datetime',
            field=models.DateTimeField(blank=True, default=rewards.helpers.calculate_expiry_datetime),
        ),
    ]
