# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-04-11 20:50
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('rewards', '0005_auto_20170412_0431'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='reward',
            name='check',
        ),
    ]
