# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-04-08 02:56
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('tags', '0001_initial'),
        ('genres', '0001_initial'),
        ('platforms', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Game',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('description', models.CharField(max_length=500)),
                ('detailed_description', models.CharField(max_length=2000)),
                ('price', models.DecimalField(decimal_places=2, max_digits=6)),
                ('release_datetime', models.DateTimeField(default=datetime.datetime(2017, 4, 8, 2, 56, 37, 211912))),
                ('image', models.ImageField(default='/static/defaultGame.png', upload_to='images/')),
                ('featured', models.BooleanField(default=False)),
                ('genre', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='genres.Genre')),
                ('platforms', models.ManyToManyField(to='platforms.Platform')),
                ('tags', models.ManyToManyField(to='tags.Tag')),
            ],
        ),
    ]
