# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-04-09 08:43
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('games', '0003_auto_20170408_1614'),
    ]

    operations = [
        migrations.AlterField(
            model_name='game',
            name='release_datetime',
            field=models.DateTimeField(default=datetime.datetime(2017, 4, 9, 16, 43, 7, 645954)),
        ),
    ]
