# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-04-09 11:12
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('games', '0004_auto_20170409_1643'),
    ]

    operations = [
        migrations.AlterField(
            model_name='game',
            name='release_datetime',
            field=models.DateTimeField(default=datetime.datetime(2017, 4, 9, 19, 12, 43, 387065)),
        ),
    ]
