# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-04-10 15:49
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('games', '0006_auto_20170410_2251'),
    ]

    operations = [
        migrations.AlterField(
            model_name='game',
            name='release_datetime',
            field=models.DateTimeField(default=datetime.datetime(2017, 4, 10, 23, 49, 9, 910754)),
        ),
    ]
