# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-04-10 16:06
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('games', '0007_auto_20170410_2349'),
    ]

    operations = [
        migrations.AlterField(
            model_name='game',
            name='release_datetime',
            field=models.DateTimeField(default=datetime.datetime(2017, 4, 11, 0, 6, 33, 427899)),
        ),
    ]
